name: Android CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Step 1: Check out the repository code
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission to gradlew
      run: chmod +x gradlew

    - name: Build debug APK
      # Step 2: Assemble the debug build using the Gradle wrapper
      run: ./gradlew assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        # Step 3: Archive and upload the generated APK file so you can download it
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
